### PR TITLE
feat-add stack Implementation

### PR DESCRIPTION
**Pull request by nagaraj28**
I just added stack implementation using array in c++ lang.
provided problem statement as well as solution.

### CODE REVIEW

**Comment by rht6226** [comment]
Your file has got no extension. Add the extension then create the PR again

**Comment by nagaraj28** [comment]
okay added extension

**Comment by rht6226** [comment]
Nice. Now please put it in the stack folder, and add the problem statement in Stack/README.md

I would like to keep the repo a bit organised. Otherwise it will be a bit messy. Don't you agree?

**Comment by nagaraj28** [comment]
yeah i will do that.

**Pull request merged**
